import os
from python.helpers.api import ApiHandler, Request, Response, send_file
from python.helpers import files

class PublicImage(ApiHandler):
    """
    Publicly accessible endpoint for serving images from the outputs directory.
    Used by external services (like Instagram) to fetch images generated by the agent.
    """

    @classmethod
    def get_methods(cls) -> list[str]:
        return ["GET"]

    @classmethod
    def requires_auth(cls) -> bool:
        # Public access required for external services to fetch the image
        return False

    async def process(self, input: dict, request: Request) -> dict | Response:
        # Get filename from query param
        filename = input.get("filename", request.args.get("filename", ""))

        if not filename:
            return Response("Filename required", status=400)

        # Security: Sanitize filename to prevent directory traversal
        # This ensures we only serve files directly inside the target directory
        clean_filename = os.path.basename(filename)

        # Allow serving only from outputs directory
        # Using get_abs_path handles the root resolution correctly
        file_path = files.get_abs_path(f"outputs/{clean_filename}")

        if not os.path.exists(file_path):
             return Response("File not found", status=404)

        # Security: Whitelist extensions
        valid_extensions = {".jpg", ".jpeg", ".png", ".gif", ".webp"}
        _, ext = os.path.splitext(clean_filename)
        if ext.lower() not in valid_extensions:
             return Response("Invalid file type", status=403)

        return send_file(file_path)
